language: php

php:
    - '7.0'
    - '7.1'
    - hhvm

before_script:
    - cp .env.travis .env
    - php artisan key:generate
    - mysql -e 'create database homestead_test;'
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit
