language: php
dist: trusty
php:
    - '7.0'
    - '7.1'

services:
  - mongodb

addons:
  sonarqube:
    token:
      secure: $SONAR_QUBE_TOKEN

before_script:
    - cp .env.travis .env
    - cp travis.phpunit.xml phpunit.xml
    - mysql -e 'create database homestead_test;'
    - echo 'date.timezone = "Asia/Bangkok"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate

script:
    - vendor/bin/phpunit --coverage-text
    - sonar-scanner
